name: megazine CI-CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Set yaml file 
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.RDS_HOST }}
          spring.datasource.username: ${{ secrets.RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
          cloud.aws.credentials.accessKey: ${{ secrets.AWS_S3_ACCESS_KEY }}
          cloud.aws.credentials.secretKey: ${{ secrets.AWS_S3_SECRET_KEY }}
          cloud.aws.s3.bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          cloud.aws.s3.region: ${{ secrets.AWS_REGION }}          

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY_ID }} 
          aws-region: ${{ secrets.AWS_S3_REGION }} 

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://springboot-megazine/$GITHUB_SHA.zip

      - name: Code Deploy
        run: 
          aws deploy create-deployment
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --application-name megazine-codedeploy
          --deployment-group-name megazine-server
          --s3-location bucket=springboot-megazine,bundleType=zip,key=$GITHUB_SHA.zip
